const mongoose = require('mongoose');
const Schema = mongoose.Schema; //const { Schema } = mongoose; 이렇게 써도 된다.

//Mongoose Schema setup후 mongoose model 생성
const aorticDataSchema = new mongoose.Schema({
    order_number: { type: Number, uinque: true, index: true },
    institution: { type: String, required: true },
    subject_number: String,
    enrollment_date: String,
    op_date: String,
    name: String,
    sex: String,
    age: Number,
    doctor: String,
    patient_number: { type: String, unique: true, required: true },
    weight: Number,
    height: Number,
    bsa: Number,
    bmi: Number,
    smoking: String,
    hb: Number,
    plt: Number,
    cr: Number,
    bun: Number,
    gfr: Number,
    dm: String,
    insulin: String,
    ckd: String,
    dialysis: String,
    ht: String,
    lung: String,
    fev1: Number,
    carotid: String,
    pvd: String,
    cerebrovasc: String,
    redo: String,
    prev_aorta_op: String,
    prev_mi: String,
    connective: String,
    cpr: String,
    tamponade: String,
    af: String,
    nyha: String,
    pre_echo: String,
    coronary: String,
    ef: Number,
    aortic_insufficiency: String,
    mitral_regurgitation: String,
    tricuspid_regurgitation: String,
    cause: String,
    rupture: String,
    elective: String,
    emergency: String,
    op_name: String,
    homograft: String,
    op_time: Number,
    cpb_time: Number,
    acc_time: Number,
    low_temp: Number,
    temp_measure: String,
    Low_body_ischemic_time: Number,
    tca: Number,
    prox_acc_location: String,
    cannulation_site: String,
    retro_cbr_pefusion: String,
    ante_cbr_perfusion_uni: String,
    cbr_perfusion_bi: String,
    selective_visc_perfusion: String,
    intercostal_reimplant: String,
    csf: String,
    cabg: String,
    aortic_valve: String,
    mitral_valve: String,
    maze: String,
    tricuspid: String,
    tevar: String,
    procedure_time: Number,
    prox_lz: String,
    dist_lz: String,
    head_vss_revasc: String,
    lsa_embo: String,
    other_proc: String,
    tevar_csf: String,
    endoleak: String,
    sine: String,
    tevar_complication_others: String,
    evar: String,
    evar_pocedure_time: Number,
    ibd: String,
    iia_embo: String,
    evar_other_proc: String,
    evar_endoleak: String,
    tevar_complication_others: String,
    discharge_date: Date,
    death: String,
    death_date: Date,
    death_cause: String,
    icu_stay: Number,
    hospital_stay: Number,
    bleeding: String,
    ami: String,
    ecmo: String,
    pul_cx: String,
    reintubation: String,
    tracheostomy: String,
    new_dialysis: String,
    colitis: String,
    gi_bleeding: String,
    stroke: String,
    neuro_deficit: String,
    cbr_lesion: String,
    cord_injury: String,
    paraplegia: String,
    wound_infection: String,
    wound_site: String    
});

module.exports = mongoose.model('AortaData', aorticDataSchema);
